### ISSUE TITLE
Registering model admin class in views.py?

### ISSUE THREAD

**Issue by tm-kn** [wagtail/wagtail-personalisation#180]
I am not quite sure if it's a good idea to register model admin class in the `views.py`. Keeping the modeladmin class & views sounds ok, but we probably should move the `modeladmin_register` call to wagtail_hooks.py as per the official documentation. I guess it gets registered as long as views.py is imported somewhere (probably `urls`), but I would not think it's reliable/future-proof/blessed by the documentation.

Commit 32748b0d6f489eb845a1dfe2d904be1e6799fceb

Docs - http://docs.wagtail.io/en/v2.1/reference/contrib/modeladmin/

**Comment by jberghoef** [comment]
It has since been replaced with a decorator. Do you reckon that solves this issue?

https://github.com/wagtail/wagtail-personalisation/commit/3eac2cd4ddd4d1cea9d31cf262a8f92e7bd84ef1#diff-e24f8bdfd28b0d554343ace9959ffd90R16
