### ISSUE TITLE
Switch to american spelling

### ISSUE THREAD

**Issue by easherma-truth** [wagtail/wagtail-personalisation#235]
IIRC, Wagtail and many other Django projects default to American English for spelling? It would be nice to have that be consistent (he said rather selfishly)

**Comment by zerolab** [comment]
Hey @easherma-truth, fwiw, https://docs.wagtail.org/en/stable/contributing/general_guidelines.html#language recommends British English, and we (well, mostly @lb-) have been updating the docs to abide by the guidelines :)

**Comment by lb-** [comment]
@easherma-truth are you referring to the spelling of documentation/docstrings or for default translations within this project's content?

Technically this project is not Wagtail and could have it's own guidelines but for now the approach in Wagtail core is British spelling. 

I know this can be a point of contention but I recall a decision had to be made and documented one way or the other a few years ago. As the Torchbox team are mostly based in the UK and most docs were already written a certain way it made sense to standardise on that spelling

**Comment by easherma-truth** [comment]
Makes sense! I think I had just mis-remembered which way the spelling went for Wagtail projects.
