### ISSUE TITLE
Move to wagtail-nest

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail-personalisation#249]
https://github.com/wagtail-nest

**Comment by easherma-truth** [comment]
@lb- I chatted with @jacobtoppm  and Scott a bit about moving this project into wagtail-nest. I'd be happy to help with maintenance and reviewing/merging pull requests in either org but would need access one way or the other. :-)

**Comment by lb-** [comment]
I think it makes sense to move this to Wagtail nest, probably best to get this raised in the core team chat. I'll flag for discussion there and see if there are any concerns.

**Comment by lb-** [comment]
Good to go from the core team perspective.

**Comment by zerolab** [comment]
Repository moved.
@easherma-truth you've got an invite

**Comment by easherma** [comment]
@lb- @zerolab thanks for the invite! 

I'm hoping to set aside some time over the next few weeks to help with maintenance of this project. As I get going, I have some questions about the publishing process. 

The version on PyPi hasn't been published or updated in some time. I read the docs on `wagtail-nest` and it seems like there is an automated workflow set up for publishing. 

Should an initial task be to update this repo to conform to those workflows? 

Or I can first work on merging some of the wagtail version updates, and then I have a small bug fix for the editor UI that I can then add on top of the version updates. Would I need someone else to review it, or could I merge it myself? This is a fix I already did in our fork of the project.

Thanks again!

**Comment by zerolab** [comment]
@easherma I usually start with bringing the setup up to date, but YMMV. ([most recent example](https://github.com/wagtail-nest/wagtail-polymath/pull/12))

As for PRs and changes - ideally you would get someone else to review your PRs, but that may not be quick. I'd say merge what you review, open PRs for the tweaks you need to make and if there's noone to review in 1-2 days for the larger/more contentious one, merge away.
