### ISSUE TITLE
Create a rest-framework based API to update visitor counts 

### ISSUE THREAD

**Issue by mvantellingen** [wagtail/wagtail-personalisation#74]
This allows us to use a CDN

**Comment by kaedroho** [comment]
To make personalisation work behind a CDN, we're also going to need to find a way to customise the content of a page on a per-user basis without rendering the page. Perhaps we should create an uncached view that returns a JSON formatted document with the segments the user is in and leave it to the developer to implement the personalised content using javascript?

**Comment by kaedroho** [comment]
Also, this should be simple enough to implement with a Django view

**Comment by robmoorman** [comment]
Think so, the JSON formatted page already has a good structure (if you have provided the fields). In that case more client-side applications, like some heavy React based apps, can be personalized  in any developer chosen way. Even mobile apps should be possible I guess.
